version: '3.4'

services:
  cashplataform.api:
    image: cashplataformapi
    build:
      context: .
      dockerfile: src/Services/CashPlataform.API/Dockerfile
    depends_on:
      - nosql.server

  nosql.server:
    image: mongo